baseURL: "https://danielwagner.at/"
languageCode: "en-us"
title: "Daniel Wagner"
# copyright: "Structegra Digital Strategy  e.U."
paginate: 5
theme: PaperMod

enableGitInfo: true
enableRobotsTXT: true
# buildDrafts: false
# buildFuture: false
# buildExpired: false

# googleAnalytics: G-YCDFRMP3XS

minify:
  disableXML: true
  minifyOutput: true

params:
  # env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Daniel Wagner
  description: "Blog and Website of Daniel Wagner and Structegra Digital Strategy e.U. on information technology, software engineering, cloud, linux, volunteering at CoderDojo and personal stuff"
  keywords: [Blog, "Daniel Wagner", "Structegra Digital Strategy e.U.", "Enterprise Architecture", "Digitalization", "IT Governance", "IT Strategy", "Compliance", "Consulting", "Training", "IT", "DevOps", "Tulln", "Vienna", "Austria"]
  author: Daniel Wagner
  # author: ["Me", "You"] # multiple authors
  images: ["/img/logo.webp", "/img/profile-image.webp"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShareButtons: []
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  mainSections:
  - posts
  
  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    # favicon: "<link / abs url>"
    # favicon16x16: "<link / abs url>"
    # favicon32x32: "<link / abs url>"
    # apple_touch_icon: "<link / abs url>"
    # safari_pinned_tab: "<link / abs url>"
    
  label:
    text: "Home"
    icon: /img/logo.webp
    iconHeight: 35

  profileMode:
    enabled: true # needs to be explicitly set
    title: Daniel Wagner
    subtitle: "Helping people improve"
    imageUrl: "img/profile-image.webp"
    imageWidth: 200
    imageHeight: 200
    imageTitle: "Portrait of Daniel Wagner"
    buttons:
      - name: about
        url: page/about
      - name: offering
        url: page/offering
      - name: posts
        url: posts
      - name: projects
        url: projects

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog

  socialIcons:
    - name: email
      url: "mailto:daniel@structegra.eu"
    - name: github
      url: "https://github.com/danielwagn3r"
    - name: gitlab
      url: "https://gitlab.com/danielwagn3r"
    - name: linkedin
      url: "https://www.linkedin.com/in/danielwagn3r"
    - name: facebook
      url: "https://www.facebook.com/daniel.wagn3r"
    - name: instagram
      url: "https://www.instagram.com/dani3lwagner"
    - name: mastodon
      url: "https://fedi.at/@danielwagn3r"
    - name: bluesky
      url: "https://bsky.app/profile/danielwagn3r.bsky.social"
    - name: signal
      url: "https://signal.me/#eu/UCZWhbznyhhjuJ6S0by1TXbBsyNGrGQDexOyNVGoZblGsGAO6W1JiK23CRulSh8r"
    - name: twitter
      url: "https://twitter.com/daniel_wagn3r"
    - name: rss
      url: "index.xml"

  analytics:
    # google:
    #   SiteVerificationTag: "G-YCDFRMP3XS"
    # bing:
    #   SiteVerificationTag: "XYZabc"
    # yandex:
    #   SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page
    linkFullImages: false
  

  editPost:
    URL: "https://github.com/danielwagnerEU/danielwagnereu.github.io/blob/main/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - identifier: about
      name: about me
      url: /page/about/
      weight: 10
    - identifier: offering
      name: offering
      url: /page/offering/
      weight: 20
    - identifier: posts
      name: posts
      url: /posts/
      weight: 30
    - identifier: projects
      name: projects
      url: /projects/
      weight: 40
    - identifier: categories
      name: categories
      url: /categories/
      weight: 50
    - identifier: tags
      name: tags
      url: /tags/
      weight: 60
    - identifier: search
      name: search
      url: /search
      weight: 70
    - identifier: press
      name: media
      url: /page/media
      weight: 80
    # - identifier: example
    #   name: example.org
    #   url: https://example.org
    #   weight: 50

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
